# Building a Neural Network from scratch


## Context
A neural network (NN) is composed of layers. An $\textit{input layer}$ where a single or vector of inputs can be fed into the NN, and an $\textit{output layer}$, again the output could be singular (scalar) or contain a vector of outputs, and in the middle, $\textit{hidden layers}$. These hidden layers are where the magic happens. Shallow NNs have one hidden layer with multiple $\textit{nodes}$ whearas deep NNs contain multiple hidden layers.  

## The magic
As we said above, the hidden layers are filled with nodes. Each node has a $\textit{weight}$ that comes with it which is updated with each pass back through the network (backpropagation). Each hidden layer also comes with a $\textit{bias}$ that gets added to the weights at each layer. We train the NN by feeding through some training $x$ data, then use the NN, initialised with random weights, to predict an output $y$, whereupon a loss function will determine how "correct" the weights are. We then use the optimizer to perform backpropagation through the network to update the weights according to the loss function, whereupon we then feed through more $x$ data. We repeat the process until the loss function is below a certain tolerance.

## Risks 
#### Overfitting
Training the network by letting it go through the training data over and over again (epochs) is a good way to fit your training data well, but the network will likely not be $\textit{generalisable}$ to your test data. This is why we have $\textit{regularisation}$, where larger values for the loss function are punished to avoid the weights changing drastically. There are other ways to regularise NNs as well.

#### Vanishing gradients
This was an early problem in training deep neural networks, where each pass of backpropagation causes the gradients to become smaller and smaller, until the weights stop updating all together. To fix this, we introduce the $\textit{ReLU}$ function, where the outputs of a layer are clamped to never go below 0, solving the vanishing gradients problem. 

<img src="figure/NN.png" alt="NN" width="500px" style="display:flex;align-items:center;">

Figure 1: Typical NN with an input layer, three hidden layers, and an output layer.

## This project
In this project, we build a neural network from scratch, only using numpy to compute mathematical oporations such as ```np.dot(x,y)```. We will then train this neural network on the MNIST numbers dataset and evaluate its performance. If it does well, we can also evaluate it on the fashion MNIST dataset. 

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Coding one Neuron

In [33]:
class Neuron:
    def __init__(self, weight, biases, input):
        self.weight = weight
        self.biases = biases
        self.input = input
        self.output = 0 
    
    def forward(self) -> float:
        self.output = self.input * self.weight + self.biases
        return self.output

In [34]:
w = np.random.uniform(0, 5, 1)
b = np.random.uniform(0, 5, 1)
X_data = np.random.uniform(0, 100, 5)

neuron = Neuron(weight=w, biases=b, input=X_data)
output = neuron.forward()

print(output)

[ 2.15225425 52.76403725 97.41714428 73.86410913 74.46712997]
[ 12.47722093 205.41134622 375.63076223 285.84565756 288.14439693]


## Whole Network of hidden layers and neurons

In [32]:
def normalise(weights: np.ndarray)-> np.ndarray:
    w_max = np.max(weights)
    w_min = np.min(weights)
    return (weights - w_min) / (w_max - w_min)

In [38]:
class NeuralNetwork:
    def __init__(self, num_inputs, num_hidden_layers, num_nodes_per_layer, num_outputs):
        self.num_inputs = num_inputs
        self.num_hidden_layers = num_hidden_layers
        self.num_nodes = num_nodes_per_layer
        self.num_outputs = num_outputs
        
        # Randomly initiate weights and biases
        self.weights = np.random.uniform(0, 1, size=(num_nodes_per_layer, num_hidden_layers))
        self.biases = np.random.uniform(0, 1, num_hidden_layers)
        
        print("Weights", self.weights)
        print("Biases", self.biases)

In [39]:
NN = NeuralNetwork(2, 3, 5, 1)

Weights [[0.97327129 0.73562748 0.80899505]
 [0.54968341 0.12554884 0.4834323 ]
 [0.30622101 0.7458391  0.43188555]
 [0.46147441 0.29919917 0.03056877]
 [0.98235976 0.86098459 0.69796089]]
Biases [0.02538337 0.30151955 0.52350809]
